### PR TITLE
bump to 2.7.12

### PR DESCRIPTION
**Pull request by mcg1969**
Simple version bump.
New dependency on filelock; all other dependencies identical:
https://github.com/snowflakedb/snowflake-connector-python/blob/main/setup.cfg#L60
The refactoring investment for 2.7.11 pays off :-)

### CODE REVIEW

**Review by katietz — COMMENTED** [review]
no win64 build?

**Comment by skupr-anaconda** [comment]
LGTM. Although win-64 artifacts can be missing on Prefect after merging.

**Comment by mcg1969** [comment]
Indeed I want to diagnose the win-64 issue before merging. The failure seems to be after the upload stage but I am not sure if all artifacts are being built.

**Review by varlackc — COMMENTED** [review]
https://github.com/AnacondaRecipes/snowflake-connector-python-feedstock/blob/91d55df50bf5cc58158caf761f957e85decdf5d2/recipe/meta.yaml#L83&L84

If we use `( || true ) or ( || 1)` the `pip check` test will seem to pass always.
In such case we might not be able to rely on the results on the package. 

Since we can not rely on the default testing in this case, the question might be how can we ensure that the package will not introduce regressions.

**Comment by mcg1969** [comment]
That's a good point, @varlackc; let me look at the logs and see if maybe we can drop that short-circuit.

**Pull request merged**
